collections:
  readers:
    output: true
  books:
  parts:
  summaries:
    output: true
  groups:
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "readers"
    values:
      layout: "reader"
  - scope:
      path: ""
      type: "summaries"
    values:
      layout: "summary"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
    values:
      layout: "default"