collections:
  users:
    output: true
    permalink: /mitwirkende/:name
  summaries:
    output: true
    permalink: /lesefassung/:title
  groups:
  characters:
    output: true
    permalink: /charaktere/:name

defaults:
  - scope:
      path: ""
      type: "users"
    values:
      layout: "user"
  - scope:
      path: ""
      type: "summaries"
    values:
      layout: "summary"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
    values:
      layout: "default"