collections:
  readers:
    output: true
  chapters:
    output: true

defaults:
  - scope:
      path: ""
      type: "readers"
    values:
      layout: "reader"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapters"
  - scope:
      path: ""
    values:
      layout: "default"