collections:
  users:
    output: true
  books:
  parts:
  summaries:
    output: true
  groups:
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "users"
    values:
      layout: "user"
  - scope:
      path: ""
      type: "summaries"
    values:
      layout: "summary"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
    values:
      layout: "default"